numpy Session

In [50]:
import numpy as np


# Creating Array Using numpy

In [88]:
#1-D Array
food1=np.array(["samosa","pakora","raita"])
food1

array(['samosa', 'pakora', 'raita'], dtype='<U6')

In [94]:
price=np.array([5,5,5])
price

array([5, 5, 5])

In [90]:
type(food1)

numpy.ndarray

In [54]:
len(price) 

3

In [91]:
price[2]

5

In [55]:
food1[0:]

array(['samosa', 'pakora', 'raita'], dtype='<U6')

In [56]:
price[0:]

array([5, 5, 5])

In [95]:
price.mean()

5.0

In [58]:
# zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [59]:
#ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [60]:
#empty
np.empty(4)

array([ 25.,  50.,  75., 100.])

In [61]:
# Empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [62]:
# Range
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [98]:
#Specify
np.arange(2, 20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [99]:
np.arange(2,22,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [65]:
# Table of 5
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [66]:
# Linespace
np.linspace(0,100,num=5)

array([  0.,  25.,  50.,  75., 100.])

In [67]:
np.ones(10,dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [102]:
np.ones(10,dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Array function

In [69]:
a=np.array([10,12.3,5,45,34,56,56.4])
a

array([10. , 12.3,  5. , 45. , 34. , 56. , 56.4])

In [70]:
a.sort()
a

array([ 5. , 10. , 12.3, 34. , 45. , 56. , 56.4])

In [71]:
b=np.array([12.43,34,45,67,89,87.9])
b

array([12.43, 34.  , 45.  , 67.  , 89.  , 87.9 ])

In [72]:
# concatenate
c=np.concatenate((a,b))
c

array([ 5.  , 10.  , 12.3 , 34.  , 45.  , 56.  , 56.4 , 12.43, 34.  ,
       45.  , 67.  , 89.  , 87.9 ])

In [73]:
c.sort()
c

array([ 5.  , 10.  , 12.3 , 12.43, 34.  , 34.  , 45.  , 45.  , 56.  ,
       56.4 , 67.  , 87.9 , 89.  ])

# 2- D Array

In [106]:
a=np.array([[1,2,3],[4,5,4]])
a

array([[1, 2, 3],
       [4, 5, 4]])

In [107]:
b=np.array([[6,7,8],[9,8,9]])
b

array([[6, 7, 8],
       [9, 8, 9]])

In [112]:
c=np.concatenate((a,b),axis=0)
c

array([[1, 2, 3],
       [4, 5, 4],
       [6, 7, 8],
       [9, 8, 9]])

In [110]:
c=np.concatenate((a,b),axis=1)
c

array([[1, 2, 3, 6, 7, 8],
       [4, 5, 4, 9, 8, 9]])

# 3- D Array

In [77]:
a=np.array([[[1,2,3,4],
[5,6,7,8]],
[[1,2,3,4],
[5,6,7,8]],
[[1,2,3,4],
[5,6,7,8]]])
a

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [113]:
# to find  find the number of dimension
a.ndim

2

In [114]:
b=np.array([[1,2],
[3,4],
[5,6]])
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [115]:
b.ndim

2

In [81]:
a.size

24

In [82]:
b.size

6

In [83]:
a

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [84]:
a.shape

(3, 2, 4)

In [85]:
a=np.arange(49)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48])

In [86]:
a=a.reshape(7,7)
a

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [87]:
a.ndim

2